server:
  error:
    include-stacktrace: never
spring:
  application:
    name: Order Service
  datasource:
    url: jdbc:mysql://localhost:3306/db_order_service?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

broker:
  exchange: orders.exchange
  routingkey:
    orderCreated: order.created
    stockReserved: stock.reserved
  queue:
    orderStatus: order.status.queue
    stockReservation: stock.reservation.queue

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace